version: '3.8'

services:
  postgres:
    container_name: postgres_container
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: datakage
      POSTGRES_PASSWORD: digitalskola2024
      POSTGRES_DB: project_2
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python:
    image: python:3.9
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./app:/app
    working_dir: /app/dbt_project_test
    depends_on:
      - postgres
    command: bash -c "pip install dbt-core dbt-postgres && tail -f /dev/null"

volumes:
  postgres_data:
