FROM postgres:latest

ENV POSTGRES_USER=datakage
ENV POSTGRES_PASSWORD=digitalskola2024
ENV POSTGRES_DB=project_2

# if you want to check the result on local
EXPOSE 5432

COPY ./schema.sql /docker-entrypoint-initdb.d/