# Use the official Python image from the Docker Hub
FROM python:3.9

# Install PostgreSQL client
RUN apt-get update && apt-get install -y postgresql-client

# Set the working directory
WORKDIR /app

# Install DBT core and DBT Postgres adapter
RUN pip install dbt-core dbt-postgres

# Copy the rest of the application code
COPY ./app /app

# Default command
CMD ["tail", "-f", "/dev/null"]
