name: 'dbt_project_test'
version: '1.0.0'
config-version: 2

profile: dbt_project_test

# These specify where dbt will look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

# Defining models configuration
models:
  dbt_project_test:
    # Default configurations for all models
    materialized: table

# Configuring paths for documentation and tests
test-paths: ["tests"]
docs-paths: ["docs"]

# Configuring packages
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.6

# Configuring on-run-start and on-run-end hooks
on-run-start: []
on-run-end: []

# Configuring vars
vars: {}
