version: 2

sources:
  - name: dim_categories
    - tables:
      - name: dim_categories
  - name: dim_customers
    - tables:
      - name: dim_customers
  - name: dim_employees
    - tables:
      - name: dim_employees
  - name: fact_order_details
    - tables:
      - name: fact_order_details
  - name: fact_orders
    - tables:
      - name: fact_orders
  - name: dim_products
    - tables:
      - name: dim_products
  - name: dim_regions
    - tables:
      - name: dim_regions
  - name: dim_shippers
    - tables:
      - name: dim_shippers
  - name: dim_suppliers
    - table:
      - name: dim_suppliers
  - name: dim_territories
    - tables:
      - name: dim_territories
